version: '3.8'
services:
  blog-client:
    image: node:16
    container_name: blog-client
    tty: true
    volumes:
      - ./client:/home/client
    ports:
      - 3000:3000
    environment:
      TZ: "Asia/Tokyo"
      HOST: "0.0.0.0"
    working_dir: /home/client
    depends_on:
      - blog-nginx
  blog-api:
    build: api
    container_name: blog-api
    tty: true
    volumes:
      - ./api:/var/www/html
    environment:
      TZ: "Asia/Tokyo"
    depends_on:
      - blog-db
  blog-nginx:
    image: nginx:1.21
    container_name: blog-nginx
    ports:
      - 8080:8080
    volumes:
      - ./api:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    environment:
      TZ: "Asia/Tokyo"
    depends_on:
      - blog-api
  blog-db:
    image: mysql:5.7
    container_name: blog-db
    volumes:
        - ./mysql_lib:/var/lib/mysql
        - ./mysql_conf:/etc/mysql/conf.d
        - ./mysql/docker-entrypoint-initdb.d
    environment:
            MYSQL_DATABASE: main
            MYSQL_USER: docker
            MYSQL_PASSWORD: docker
            MYSQL_ROOT_PASSWORD: root
            TZ: "Asia/Tokyo"
    command: "mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci"